modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="jei_diet_filter"
version="1.0.0"
displayName="JEI Diet Filter"
displayTest="IGNORE_ALL_VERSION"
description='''Adds a "!" prefix to the JEI search box to show only foods not yet eaten according to Diet.'''

[[dependencies.jei_diet_filter]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.jei_diet_filter]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.jei_diet_filter]]
modId="jei"
mandatory=true
versionRange="[15.20.0.129,)"
ordering="NONE"
side="BOTH"

[[dependencies.jei_diet_filter]]
modId="solcarrot"
mandatory=true
versionRange="[1.15,)"
ordering="NONE"
side="BOTH"
